pipeline {
    agent any
    
    environment {
        AWS_ACCESS_KEY_ID = credentials ('aws-access-key-id')
        AWS_SECRET_ACCESS_KEY = credentials ('aws-secret-access-key')
        AWS_DEFAULT_REGION = 'us-east-2'
        WEB_TAG = 'web'
        APP_TAG = 'app'
    }

    parameters {
        choice(
        name: 'TF_ACTION',
        choices: ['COPY_NGINX_FILES', 'COPY_PYTHON_FILES', 'DEPLOY_PYTHON_APP', 'DEPLOY_NGINX_WEB_APP'],
        description: 'Select Action To Perform'
      )
    }

    stages {
        stage ('Copy nginx files') {
        when {
            expression {params.TF_ACTION == 'COPY_NGINX_FILES'}
        }
            // This step fetches web server private ip installs and starts nginx fetches public ip
            // of python app server and sed command it into index.html file      
            steps {
                 sshagent (credentials: ['AWS-SSH-KEY']) {
                sh '''
              WEB_INSTANCE_PRIVATE_IP=$(aws ec2 describe-instances \
                --instance-ids $(aws elbv2 describe-target-health \
                      --target-group-arn arn:aws:elasticloadbalancing:us-east-2:568298704568:targetgroup/public-tg/6a8c122b802f3972 \
                      --query 'TargetHealthDescriptions[?TargetHealth.State==`healthy`].Target.Id' \
                      --output text | awk '{print $1}') \
                      --query 'Reservations[0].Instances[0].PrivateIpAddress' \
                      --output text)
                
                scp -o StrictHostKeyChecking=no $WORKSPACE/jenkins-files/deployments/nginx-deploy.sh ubuntu@$WEB_INSTANCE_PRIVATE_IP:/home/ubuntu/nginx-deploy.sh
                scp -o StrictHostKeyChecking=no $WORKSPACE/jenkins-files/deployments/namecheap-ddns.sh ubuntu@$WEB_INSTANCE_PRIVATE_IP:/home/ubuntu/namecheap-ddns.sh                
                
                '''
                 }
            }
        }

        stage ('Deploy Web App') {
            when {
            expression {params.TF_ACTION == 'DEPLOY_NGINX_WEB_APP'}
        }
            steps {
            sh '''
                    INSTANCE_ID=$(aws elbv2 describe-target-health \
                    --target-group-arn arn:aws:elasticloadbalancing:us-east-2:568298704568:targetgroup/public-tg/6a8c122b802f3972 \
                    --query 'TargetHealthDescriptions[?TargetHealth.State==`healthy`].Target.Id | [0]' \
                    --output text)

                    if [ -z "$INSTANCE_ID" ] || [ "$INSTANCE_ID" = "None" ]; then
                    echo "ERROR: No healthy instances found in target group"
                    exit 1
                    fi

                    echo  "Using instance: $INSTANCE_ID"
                    
                    aws ssm send-command \
                         --instance-ids "$INSTANCE_ID" \
                         --document-name "AWS-RunShellScript" \
                         --comment "Deploy to web tier" \
                         --parameters commands="[
                         \"sudo chmod +x /home/ubuntu/nginx-deploy.sh\",
                         \"/home/ubuntu/nginx-deploy.sh\"
                         ]" \
                         --region ${AWS_DEFAULT_REGION}
                '''
            }
        }

        // This stage fetches python app server public ip, ssh into it, copies python service 
        // file into it and activate important binaries. it then clones the repo and starts 
        // the python app server    
        stage ('Copy files to Backend Server') {
        when {
            expression {params.TF_ACTION == 'COPY_PYTHON_FILES'}
        }
            steps {
                 sshagent (credentials: ['AWS-SSH-KEY']) {
                sh '''

                PYTHON_INSTANCE_PRIVATE_IP=$(aws ec2 describe-instances \
                --instance-ids $(aws elbv2 describe-target-health \
                      --target-group-arn arn:aws:elasticloadbalancing:us-east-2:568298704568:targetgroup/private-tg/d9960bdf046182d7 \
                      --query 'TargetHealthDescriptions[?TargetHealth.State==`healthy`].Target.Id' \
                      --output text | awk '{print $1}') \
                      --query 'Reservations[0].Instances[0].PrivateIpAddress' \
                      --output text)
                
                scp -o StrictHostKeyChecking=no $WORKSPACE/jenkins-files/deployments/fruits.service ubuntu@$PYTHON_INSTANCE_PRIVATE_IP:/tmp/fruits.service
                scp -o StrictHostKeyChecking=no $WORKSPACE/jenkins-files/deployments/python-deploy.sh ubuntu@$PYTHON_INSTANCE_PRIVATE_IP:/home/ubuntu/python-deploy.sh 
                '''
                 }
            }

        }

    stage ('Deploy App to Backend Server') {
          when {
            expression {params.TF_ACTION == 'DEPLOY_PYTHON_APP'}
        }
        steps {
        sh '''
                    INSTANCE_ID=$(aws elbv2 describe-target-health \
                    --target-group-arn arn:aws:elasticloadbalancing:us-east-2:568298704568:targetgroup/private-tg/d9960bdf046182d7 \
                    --query 'TargetHealthDescriptions[?TargetHealth.State==`healthy`].Target.Id | [0]' \
                    --output text)

                    if [ -z "$INSTANCE_ID" ] || [ "$INSTANCE_ID" = "None" ]; then
                    echo "ERROR: No healthy instances found in target group"
                    exit 1
                    fi

                    echo  "Using instance: $INSTANCE_ID"
                    
                    aws ssm send-command \
                         --instance-ids "$INSTANCE_ID" \
                         --document-name "AWS-RunShellScript" \
                         --comment "Deploy to web tier" \
                         --parameters commands="[
                         \"sudo chmod +x /home/ubuntu/python-deploy.sh\",
                         \"/home/ubuntu/python-deploy.sh\"
                         ]" \
                         --region ${AWS_DEFAULT_REGION}
                '''
        }
    }
    }
    post {
        success {
            echo 'App deployed successfully'
        }

        failure {
            echo 'App deployment failed'
        }
    }
}
