pipeline {
    agent any
    
    environment {
        AWS_ACCESS_KEY_ID = credentials ('aws-access-key-id')
        AWS_SECRET_ACCESS_KEY = credentials ('aws-secret-access-key')
        AWS_DEFAULT_REGION = 'us-east-2'
    }

    parameters {
        choice(
        name: 'TF_ACTION',
        choices: ['DEPLOY_PYTHON_APP', 'DEPLOY_NGINX_WEB_APP'],
        description: 'Select Action To Perform'
      )
    }

    stages {
        stage ('Deploy Web App Nginx') {
        when {
            expression {params.TF_ACTION == 'DEPLOY_NGINX_WEB_APP'}
        }
            // This step fetches web server private ip installs and starts nginx fetches public ip
            // of python app server and sed command it into index.html file      
            steps {
                 sshagent (credentials: ['AWS-SSH-KEY']) {
                sh '''
                WEB_INSTANCE_PRIVATE_IP=$(aws ec2 describe-instances --filters "Name=tag:Name,Values=web-instance" \
                --query "Reservations[0].Instances[0].PrivateIpAddress" \
                --output text)


                scp -o StrictHostKeyChecking=no $WORKSPACE/jenkins-files/deployments/nginx-deploy.sh ubuntu@$WEB_INSTANCE_PRIVATE_IP:/home/ubuntu/nginx-deploy.sh

                ssh -o StrictHostKeyChecking=no ubuntu@$WEB_INSTANCE_PRIVATE_IP << 'EOF'
                sudo chmod +x nginx-deploy.sh
                ./nginx-deploy.sh
                '''

                
                 }
            }
        }

        // This stage fetches python app server public ip, ssh into it, copies python service 
        // file into it and activate important binaries. it then clones the repo and starts 
        // the python app server    
        stage ('Deploy Python App') {
        when {
            expression {params.TF_ACTION == 'DEPLOY_PYTHON_APP'}
        }
            steps {
                 sshagent (credentials: ['AWS-SSH-KEY']) {
                sh '''
                 PYTHON_INSTANCE_PRIVATE_IP=$(aws ec2 describe-instances --filters "Name=tag:Name,Values=python-instance" --query "Reservations[0].Instances[0].PrivateIpAddress" --output text)

                scp -o StrictHostKeyChecking=no $WORKSPACE/jenkins-files/deployments/fruits.service ubuntu@$PYTHON_INSTANCE_PRIVATE_IP:/tmp/fruits.service
                scp -o StrictHostKeyChecking=no $WORKSPACE/jenkins-files/deployments/python-deploy.sh ubuntu@$PYTHON_INSTANCE_PRIVATE_IP:/home/ubuntu/python-deploy.sh

                ssh -o StrictHostKeyChecking=no ubuntu@$PYTHON_INSTANCE_PRIVATE_IP << EOF
                sudo chmod +x python-deploy.sh
                ./python-deploy.sh
                '''
                 }
            }

        }
    }

    post {
        success {
            echo 'App deployed successfully'
        }

        failure {
            echo 'App deployment failed'
        }
    }


}